version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    volumes:
      - ./lib:/usr/src/app/lib:rw
    command: "/usr/src/app/do-build.sh"
