name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: docker-compose -f docker-compose.test.yml up --build --exit-code-from app
