name: Generate and publish API documentation

on:
  release:
    types: [created]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: docker-compose -f docker-compose.docs.yml up --build --exit-code-from app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/api
